live_config_reload = true

[window]
startup_mode = "Fullscreen"

[shell]
program = "/bin/bash"
args = ["-l", "-c", "tmux attach"]

[font]
size = 11

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"
